### ISSUE TITLE
Discord inactive

### ISSUE THREAD

**Issue by vinliao** [scsibug/nostr-rs-relay#11]
The Discord link in README is inactive. It seems to me Nostr-Rust related things are moved to https://github.com/rajarshimaitra/rust-nostr (I've joined the Discord link over there). The Discord link in this project's README can be changed to that link. 

And, oh, by the way, do you have plans to deprecate this project, since there's rust-nostr now, @scsibug?

**Comment by scsibug** [comment]
No, there are no plans to deprecate this project.  "Nostr-rust" is a fork of this, but only because Raj and I had disagreements over whether to be fully compatible with future Nostr events.  He is free to take the code and use it for any projects he want to start, but that has no impact on the goals of "nostr-rs-relay", which will continue to provide a small, fast, correct, and full nostr implementation (all current/future event types conforming to NIP-01).

**Comment by scsibug** [comment]
I've updated the Discord link. The old one expired, the new one has no expiration.
