### ISSUE TITLE
Tag search is broken for hex-looking string values in postgres

### ISSUE THREAD

**Issue by lez** [scsibug/nostr-rs-relay#191]
According to NIP-01 only `#p` and `#e` filters are to be converted from hex. The code (line 816) converts any single-letter filter values that are strings, but look like hex into binary.
It seems prefix search has not been removed from there completely. (checks `.len() %2` instead of `.len() == 64`)
I think all this conversion should be done during parsing (deserializing) the filter, not during building the query because it makes complicated SQL.
What do you think?

**Comment by scsibug** [comment]
I'm not as familiar with the postgres code, but I can comment on what the idea was for the binary encoding in the first place.

NIP-01 has become more specific to mandate e/p tags are 64-char hex strings, although I don't think it was originally quite that strong.  And, as you noted, the prefix search meant that we saw more variety from filter parameters.

For Sqlite, we got significant savings for disk and index event representations by taking any tag values that look like hex (those that use chars 0-9a-f and have an even number of chars), and storing them as BLOBs instead of TEXT.  We always convert the BLOBs back to hex representations.

Is there a specific example of a query that does not work in Postgres?

**Comment by lez** [comment]
I see the reason of the prefix matching code now.

The query `t=a` won't return any results because the condition for `has_plain_values` doesn't include odd-length strings of hex only chars. It shows a syntax error triggered by `AND ()`:

`2024-03-30T21:18:05.048449Z ERROR nostr_rs_relay::repo::postgres: Query failed: error returned from database: syntax error at or near ")" SELECT e."content", e.created_at FROM "event" e WHERE e.id IN (SELECT ee.id FROM "event" ee LEFT JOIN tag t on ee.id = t.event_id WHERE ee.hidden != 1::bit(1) and (t."name" = $1 AND ()))) AND e.hidden != 1::bit(1) AND (e.expires_at IS NULL OR e.expires_at > now()) ORDER BY e.created_at ASC LIMIT 1000 ReqFilter { ids: None, kinds: None, since: None, until: None, authors: None, limit: None, tags: Some({'x': {"a"}}), force_no_match: false }`

https://github.com/scsibug/nostr-rs-relay/pull/192
