### ISSUE TITLE
Trying to run nostr relay in a Raspberry Pi 4

### ISSUE THREAD

**Issue by wchancao** [scsibug/nostr-rs-relay#21]
Hi, im trying to run the nostr-relay in a Raspberry Pi 4 running Raspi OS Lite 64 bits. When i run `docker build -t nostr-rs-relay .` i get this:

```
Step 2/24 : RUN USER=root cargo new --bin nostr-rs-relay
 ---> [Warning] The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
 ---> Running in a2d514b107fc
exec /bin/sh: exec format error
The command '/bin/sh -c USER=root cargo new --bin nostr-rs-relay' returned a non-zero code: 1
```
Is there a way to bypass this? And how? Thanks!!

**Comment by scsibug** [comment]
Sure; the dockerfile uses a hardcoded x86 base image. If you remove the @ and everything following from the FROM lines in the Dockerfile, I bet it will pull down an ARM image.

**Comment by wchancao** [comment]
Thanks!! That seems to work, but now i got this
```
Step 4/24 : COPY ./Cargo.toml ./Cargo.toml
COPY failed: file not found in build context or excluded by .dockerignore: stat Cargo.toml: file does not exist
```

**Comment by scsibug** [comment]
I got my RPi4 up and running, and it worked for me.

I've added a script (mk-platform-agnostic-dockerfile.sh) in the master branch that strips off the x86 image digests, to create a platform agnostic Dockerfile.

I've also attached the result which you could run instead of the default Dockerfile:
[Dockerfile.any-platform.txt](https://github.com/scsibug/nostr-rs-relay/files/9781267/Dockerfile.any-platform.txt)

**Comment by scsibug** [comment]
I've removed the digests from the dockerfile altogether, so this should build more easily now.

**Comment by pangyuteng** [comment]
thank you! was able to spin up the relay via the Dockerfile with ZERO problems!!
