### ISSUE TITLE
Old contact lists (kind=3) not deleted from database

### ISSUE THREAD

**Issue by aglkm** [scsibug/nostr-rs-relay#28]
Is there a reason why the relay doesn't delete old kind=3 events of the same pubkey from db?

NIP-02:
Every new contact list that gets published overwrites the past ones, so it should contain all entries. Relays and clients SHOULD delete past contact lists as soon as they receive a new one.

**Comment by scsibug** [comment]
Sounds like a bug, it should be setting the HIDDEN flag on older events from the same pubkey with that kind.

**Comment by aglkm** [comment]
Yes, I see they have hidden flag, but still consuming storage space. Those kind=3 events show up quite often.
So this is such design? For performance reasons?

**Comment by scsibug** [comment]
It is by design.  Some people will want to have historical records.  This helped debug an issue Jack was having where he noticed a client resetting contact lists, for example.

For right now, it's recommended to manually or through a cron task, delete HIDDEN events after some time period.

Perfectly fine to revisit how this is handled though, maybe we should just delete them immediately.  Patches accepted on that front, but I'm OK with status quo for now.
