### ISSUE TITLE
Sqlite DB incomplete?

### ISSUE THREAD

**Issue by rajarshimaitra** [scsibug/nostr-rs-relay#3]
From the DB schema here 
https://github.com/scsibug/nostr-rs-relay/blob/da7968efefc9a09b0442577149ccac60f096c605/src/db.rs#L39-L49
 it seems `tags` and `sig` fields are not included. Is this intentional? For some reason I am missing we don't need to persist them?
 
The schema contains `first_seen` which is not included in NIP1, probably removed in latest version. https://github.com/fiatjaf/nostr/blob/master/nips/01.md#events-and-signatures

**Comment by scsibug** [comment]
It is just unclear/confusing naming on my part.

The content field contains the *entire* event json, including the tags.  This duplicates data, but that is intentional.  This allows us to stream responses without a round trip through a json parser.  Only fields or specific tags that are searchable have a sql representation.

The `first_seen` field is not part of the spec, it is just to help me understand when the event was first seen on the relay, and is for future use relay-side only.

**Comment by scsibug** [comment]
The `sig` field is not useful for handling subscriptions, so we do not have a sql column for it.  It is also present in the raw json in the `content` field.

Next time I revise the db format I may clean up the naming.

**Comment by scsibug** [comment]
Created issue here: https://todo.sr.ht/~gheartsfield/nostr-rs-relay/20
