### ISSUE TITLE
Add --datadir option (and default value)

### ISSUE THREAD

**Issue by newearthmartin** [scsibug/nostr-rs-relay#66]
This is related to https://github.com/scsibug/nostr-rs-relay/pull/63

**Current situation:**

The default for nostr-rs-relay is to search for the config file in wherever folder you are standing on (if you are not using this option that you just merged).

**Why is it bad?**

This is a bit strange. It makes everything depend on where you are calling the command from.

**My suggestion**

Add a `datadir` option. The most common practice in this kind of services is to have a datadir option and this is the place where everything is (the db, the config files, etc). Instead/On top of having different flags for different things, having one config flag to set a directory where everything is.

There is usually a default place for this, which could be something like `$HOME/.nostr`. So you know where to put the config file, where to look for the db, etc. even if you use no parameters.

**Comment by scsibug** [comment]
This is a good suggestion, but I think it's somewhat arbitrary what the default is ($home/.nostr vs current working directory).  If I was starting over I would do the way you suggest though.

Here is the current --help documentation for reference:
```
nostr-rs-relay --help        
A nostr relay written in Rust

Usage: nostr-rs-relay [OPTIONS]

Options:
  -d, --db <DB>          Use the <directory> as the location of the database
  -c, --config <CONFIG>  Use the <file name> as the location of the config file
  -h, --help             Print help
  -V, --version          Print version
```
If you don't want to accept the defaults, you can just specify the database directory & config file separately.  Since we only have 2 files, I don't think it is too confusing to make them set independently.  This is the most flexible (setup a config in /etc/relay.conf; and your database in /data/relay), and I imagine many people will have their own preferences for where to put configs vs. data.

**Comment by newearthmartin** [comment]
It's nice to have a default, fixed location, even if arbitrary, because one can run the command from different places (command line, cron, services).

Without implementing a datadir option, you can have a set location for the db and config file. Maybe it's not too late to add that.

I run a bunch of services like this (bitcoin, geth, lighthouse, lnd, etc) and they all use a fixed location.
