### ISSUE TITLE
How can I ban a user as a relay operator?

### ISSUE THREAD

**Issue by shenjiayu** [scsibug/nostr-rs-relay#67]
Didn't find any web UI or similar to achieve this.

Thanks.

**Comment by nailuoGG** [comment]
https://github.com/scsibug/nostr-rs-relay/issues/65

**Comment by scsibug** [comment]
All events can now be passed to an external gRPC server.  That will allow decisions such as blocking all events by pubkey, IP, etc. to be made.  So, you can implement any policy you desire, and web UIs could be built on top of that as well.

I imagine there are a wide variety of things people want to do with respect to policy and UI.  In order to keep the main codebase small and manageable, I'm encouraging people to build on via these gRPC extensions.
